export interface WordWolfPresetTopic {
  majorityWord: string;
  minorityWord: string;
}

export const PRESET_WORD_WOLF_TOPICS: WordWolfPresetTopic[] = [
  { majorityWord: 'カレーライス', minorityWord: 'ハヤシライス' },
  { majorityWord: '犬', minorityWord: '猫' },
  { majorityWord: '海', minorityWord: '山' },
  { majorityWord: 'ディズニーランド', minorityWord: 'ディズニーシー' },
  { majorityWord: '夏休み', minorityWord: '冬休み' },
  { majorityWord: '映画館', minorityWord: 'カラオケ' },
  { majorityWord: 'コーヒー', minorityWord: '紅茶' },
  { majorityWord: '電車', minorityWord: 'バス' },
  { majorityWord: '体育', minorityWord: '音楽' },
  { majorityWord: 'スマホ', minorityWord: 'パソコン' },
  { majorityWord: 'おなら', minorityWord: 'しゃっくり' },
  { majorityWord: '5億年ボタン押す', minorityWord: '5億円のデスゲーム' },
  { majorityWord: '初めてのおつかい', minorityWord: '初めてのキス' },
  { majorityWord: 'ラーメン二郎', minorityWord: '家系ラーメン' },
  { majorityWord: '片思い', minorityWord: '両思い' },
  { majorityWord: '初デート', minorityWord: 'ダブルデート' },
  { majorityWord: 'ファーストキス', minorityWord: '初恋' },
  { majorityWord: '結婚', minorityWord: '同棲' },
  { majorityWord: '告白', minorityWord: 'プロポーズ' },
  { majorityWord: '絵本', minorityWord: 'エロ本' },
  { majorityWord: '初恋の人', minorityWord: '元カレ/元カノ' },
  { majorityWord: '理想のタイプ', minorityWord: '本命の相手' },
  { majorityWord: '修学旅行', minorityWord: '林間学校' },
  { majorityWord: '体育祭', minorityWord: '文化祭' },
  { majorityWord: '夏休みの宿題', minorityWord: '冬休みの宿題' },
  { majorityWord: 'テスト勉強', minorityWord: '定期テスト' },
  { majorityWord: '愛', minorityWord: '金' },
];

export const PRESET_WORD_WOLF_EXAMPLE_TALKS: string[] = [
  '（これの第一印象は？）',
  '（あなたはこれを好きですか？）',
  '（どんな時にこれを使いますか？）',
  '（これを一言で表すと？）',
  '（これを人におすすめするなら何て言う？）',
  '（これの良いところを1つだけ言うなら？）',
  '（これって朝と夜どっちのイメージ？）',
  '（これを知らない人に短く説明すると？）',
  '（これを選ぶ人ってどんなタイプ？）',
  '（これに点数をつけるなら何点？）',
  '（これを使う頻度は高い？低い？）',
  '（これに合う場所はどこ？）',
  '（これを一緒にやるなら誰とやりたい？）',
  '（これのテンション感は高め？落ち着き系？）',
  '（これがないとちょっと困る？）',
  '（これって子ども向け？大人向け？）',
  '（これを初めて体験した時の印象は？）',
  '（これを選ぶ決め手は何？）',
  '（これって一人向き？みんな向き？）',
  '（これを思い出す季節は？）',
  '（これをテーマにした映画や本があるとしたらどんな内容？）',
  '（これを擬人化するとどんなキャラ？）',
  '（これの反対のものは何？）',
  '（これを表す色は何色？）',
  '（これを動物に例えると？）',
  '（これを食べ物に例えると？）',
  '（これを乗り物に例えると？）',
  '（これを天気に例えると？）',   
  '（これを音楽に例えると？）',
  '（これを漫画やアニメのキャラに例えると？）',
  '（これを有名人に例えると？）',
  '（これをスポーツに例えると？）',
  '（これを季節に例えると？）',
  '（これを国に例えると？）',
  '（これを色に例えると？）',
  
];
