import { DRAW_GUESS_TOPICS, DRAW_GUESS_TOPICS_BY_DIFFICULTY } from '../drawGuessTopics.js';

export const DRAW_GUESS_GAME_TOPICS = DRAW_GUESS_TOPICS;
export const DRAW_GUESS_GAME_TOPICS_BY_DIFFICULTY = DRAW_GUESS_TOPICS_BY_DIFFICULTY;
