import { PRESET_WORD_WOLF_TOPICS, PRESET_WORD_WOLF_EXAMPLE_TALKS } from '../presetWordWolfTopics.js';

export const WORD_WOLF_GAME_TOPIC_PAIRS = PRESET_WORD_WOLF_TOPICS;
export const WORD_WOLF_GAME_EXAMPLE_TALKS = PRESET_WORD_WOLF_EXAMPLE_TALKS;
